### ISSUE TITLE
Unable to run command `coderoom version`

### ISSUE THREAD

**Issue by sonu3706** [nishant-jain-94/coderoom#1]
Hi,
I am unable to run the following command
coderoom version

Building coderoom into /home/chandan/coderoom/coderoom
fs.js:1001
  binding.stat(pathModule._makeLong(path), statValues);
          ^

Error: ENOENT: no such file or directory, stat '/home/chandan/coderoom/version'
    at Error (native)
    at Object.fs.statSync (fs.js:1001:11)
    at Object.statSync (/usr/local/lib/node_modules/coderoom/node_modules/graceful-fs/polyfills.js:297:22)
    at new Room (/usr/local/lib/node_modules/coderoom/dist/room.class.js:30:24)
    at planRooms (/usr/local/lib/node_modules/coderoom/dist/coderoom.js:40:16)
    at Object.build (/usr/local/lib/node_modules/coderoom/dist/coderoom.js:29:16)
    at Command.<anonymous> (/usr/local/lib/node_modules/coderoom/dist/bin/coderoom.js:13:14)
    at Command.listener (/usr/local/lib/node_modules/coderoom/node_modules/commander/index.js:301:8)
    at emitOne (events.js:96:13)
    at Command.emit (events.js:188:7)

**Comment by sonu3706** [comment]
Building coderoom into /home/chandan/coderoom/coderoom
fs.js:1001
  binding.stat(pathModule._makeLong(path), statValues);
          ^

Error: ENOENT: no such file or directory, stat '/home/chandan/coderoom/version'
    at Error (native)
    at Object.fs.statSync (fs.js:1001:11)
    at Object.statSync (/usr/local/lib/node_modules/coderoom/node_modules/graceful-fs/polyfills.js:297:22)
    at new Room (/usr/local/lib/node_modules/coderoom/dist/room.class.js:30:24)
    at planRooms (/usr/local/lib/node_modules/coderoom/dist/coderoom.js:40:16)
    at Object.build (/usr/local/lib/node_modules/coderoom/dist/coderoom.js:29:16)
    at Command.<anonymous> (/usr/local/lib/node_modules/coderoom/dist/bin/coderoom.js:13:14)
    at Command.listener (/usr/local/lib/node_modules/coderoom/node_modules/commander/index.js:301:8)
    at emitOne (events.js:96:13)
    at Command.emit (events.js:188:7)

**Comment by nishant-jain-94** [comment]
Deleted the comment and merged into the issue.
